---

env:
  node: true
  es6: true
extends:
  - 'eslint-config-airbnb-base'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'


plugins:
  - import

parserOptions:
      sourceType: module

rules:
  no-console: 0
  import/extensions: 0